version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    ports:
      - "9000:27017"
    volumes:
      - ./app/mongo:/data/db
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=<user>
      # - MONGO_INITDB_ROOT_PASSWORD=<pass>
      - MONGO_INITDB_DATABASE=db
    #     - MONGO_LOG_DIR=/dev/null
    # command: mongod --smallfiles --logpath=/dev/null

  app:
    build: ./
    container_name: app
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - "8989:8989"
